const ejs = require('ejs');
const fs = require('fs');
const _ = require('lodash');

function ejsCompiler(root, files) {
  const distFile = fs.openSync(`${root}/templates.js`, 'w');

  fs.writeSync(distFile, '// this file is generated by gulp, don not modify it.\n');
  fs.writeSync(distFile, 'const Templates = {}\n');

  _.each(files, (fileName) => {
    let content = fs.readFileSync(`${root}/${fileName}`);
    content = content.toString('utf-8');
    const compiled = ejs.compile(content, {
      cache: true,
      client: true,
      rmWhitespace: true,
      filename: fileName,
    });
    const templateName = _.trim(fileName, '.ejs');
    fs.writeSync(distFile, `Templates.${templateName} = ${compiled}\n\n`);
  });

  fs.writeSync(distFile, 'module.exports = Templates;\n');
  fs.closeSync(distFile);
}

function ejsCompile(complete) {
  ejsCompiler('src/templates', [
    'FunctionCallDetail.ejs',
  ]);
  complete();
}

exports.ejsCompile = ejsCompile;
